### ISSUE TITLE
POPL18 paper

### ISSUE THREAD

**Issue by nekketsuuu** [ranjitjhala/ranjitjhala.github.io#1]
There is a link to `/popl18` in [`research.html`](https://github.com/ranjitjhala/ranjitjhala.github.io/blob/20083e127978e9942e8654a39ffdf737b47d7f99/research.html#L48), but there is no file. Would you upload that paper?

**Comment by ranjitjhala** [comment]
Whoops, broken link -- fixed! Thanks for pointing out!
